PR40 Audit Fix
Shard-Labs/PoLido pull request #55
Opened 2022-02-08 10:46 UTC by mayorcoded

Make changes to node operator to ensure delegated funds are not locked in.

2022-02-08 10:52 UTC, idirall22 requested changes

2022-02-08 10:52 UTC, idirall22 commented on contracts/NodeOperatorRegistry.sol
> +        checkCondition(
add this check in the line 297

2022-02-08 12:55 UTC, idirall22 commented on contracts/StMATIC.sol
> +            .getOperatorInfos(false, false, true);
add test case to requestWithdraw from jailed and ejected operators

2022-02-08 13:00 UTC, idirall22 requested changes

2022-02-08 13:05 UTC, mayorcoded commented on contracts/NodeOperatorRegistry.sol
> +        checkCondition(
done

2022-02-08 16:30 UTC, idirall22 requested changes

2022-02-09 08:36 UTC, idirall22 approved these changes
LGTM

2022-02-10 12:04 UTC, idirall22 commented on contracts/StMATIC.sol
> +            .getOperatorInfos(false, false, true);
No, this _withdrawRewards is only used to check we accumulated enough rewards. in this case, we want only to request withdraw tokens from the validator.

2022-02-10 12:32 UTC, Jakic007 approved these changes

2022-02-10 12:37 UTC, idirall22 approved these changes
LGTM

2022-02-10 16:51 UTC, merged